// Generated by gencpp from file assignment1/triangle.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_TRIANGLE_H
#define ASSIGNMENT1_MESSAGE_TRIANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1
{
template <class ContainerAllocator>
struct triangle_
{
  typedef triangle_<ContainerAllocator> Type;

  triangle_()
    : sideLength(0.0)
    , clw(false)  {
    }
  triangle_(const ContainerAllocator& _alloc)
    : sideLength(0.0)
    , clw(false)  {
  (void)_alloc;
    }



   typedef float _sideLength_type;
  _sideLength_type sideLength;

   typedef uint8_t _clw_type;
  _clw_type clw;




  typedef boost::shared_ptr< ::assignment1::triangle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1::triangle_<ContainerAllocator> const> ConstPtr;

}; // struct triangle_

typedef ::assignment1::triangle_<std::allocator<void> > triangle;

typedef boost::shared_ptr< ::assignment1::triangle > trianglePtr;
typedef boost::shared_ptr< ::assignment1::triangle const> triangleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1::triangle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1::triangle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assignment1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'assignment1': ['/home/viki/ROS/Ass1/src/assignment1/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::triangle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::triangle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::triangle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::triangle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::triangle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::triangle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1::triangle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91bb36a3b1793754cf4d40aa5e809a34";
  }

  static const char* value(const ::assignment1::triangle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91bb36a3b1793754ULL;
  static const uint64_t static_value2 = 0xcf4d40aa5e809a34ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1::triangle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1/triangle";
  }

  static const char* value(const ::assignment1::triangle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1::triangle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 sideLength\n\
bool clw\n\
";
  }

  static const char* value(const ::assignment1::triangle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1::triangle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sideLength);
      stream.next(m.clw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct triangle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1::triangle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment1::triangle_<ContainerAllocator>& v)
  {
    s << indent << "sideLength: ";
    Printer<float>::stream(s, indent + "  ", v.sideLength);
    s << indent << "clw: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_TRIANGLE_H
