set(_CATKIN_CURRENT_PACKAGE "assignment1")
set(assignment1_VERSION "0.0.0")
set(assignment1_MAINTAINER "viki <viki@todo.todo>")
set(assignment1_PACKAGE_FORMAT "1")
set(assignment1_BUILD_DEPENDS "geometry_msgs" "turtlesim" "message_generation")
set(assignment1_BUILD_EXPORT_DEPENDS "geometry_msgs" "turtlesim" "message_runtime")
set(assignment1_BUILDTOOL_DEPENDS "catkin")
set(assignment1_BUILDTOOL_EXPORT_DEPENDS )
set(assignment1_EXEC_DEPENDS "geometry_msgs" "turtlesim" "message_runtime")
set(assignment1_RUN_DEPENDS "geometry_msgs" "turtlesim" "message_runtime")
set(assignment1_TEST_DEPENDS )
set(assignment1_DOC_DEPENDS )
set(assignment1_DEPRECATED "")